# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a58f7236b9f96f227ef6a5ba748d10d5fee703606b3c46687ef800984d91a4e49fbf8fc77367dbdcd761c85f8ce60dfa5f8404f51c01d816e7fb9009cdfde2be

test:
  secret_key_base: 402dfb7472dfb7d37f62dd065f65f3fd1060011b8ac6d5fad1718e8c31424d5a0c96e7324c3a3502bfbd3b4c6f370ca2384741e86f53a0efa3f4d97802ce7583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
